{% render "scripts/helper/templates/copyright-liquid.yml" %}

{% if platforms == "all" -%}
  {% assign platforms = "darwin-x64,linux-x64,win32-x64,linux-ia32,win32-ia32,linux-arm64,linux-arm" -%}
{% endif -%}
{% assign platforms = platforms | split: "," -%}

name: 'Publish the xPack {{ APP_NAME }} release'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The semver of the release'
        required: false
        default: 'current'

jobs:
{% for platform in platforms -%}
  {% if platform == "linux-x64" or platform == "win32-x64" or platform == "linux-ia32" or platform == "win32-ia32" %}
  linux-x64:
    name: 'Intel Linux {{ APP_NAME }} {% raw %}${{ github.event.inputs.version }}{% endraw %} publish release'
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 3
          submodules: true
      - name: 'Create body'
        run: |
          npm install
          cat scripts/templates/body-github-release-liquid.md | npm run liquidjs --silent -- '{ "RELEASE_VERSION": "{% raw %}${{ github.event.inputs.version }}{% endraw %}" }' >.github/workflows/body-github-release.md
          cat .github/workflows/body-github-release.md
      - name: 'Publish release'
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: '~/Work/{{ APP_LC_NAME }}-{% raw %}${{ github.event.inputs.version }}{% endraw %}/deploy/*'
          bodyFile: '.github/workflows/body-github-release.md'
          commit: 'master'
          draft: true
          name: 'xPack {{ APP_NAME }} v{% raw %}${{ github.event.inputs.version }}{% endraw %}'
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          owner: 'xpack-dev-tools'
          prerelease: true
          replacesArtifacts: true
          repo: '{{ APP_LC_NAME }}-xpack'
          tag: 'v{% raw %}${{ github.event.inputs.version }}{% endraw %}'
          token: {% raw %}${{ secrets.PUBLISH_TOKEN }}{% endraw %}
      - name: 'Show SHA'
        run: cat ~/Work/{{ APP_LC_NAME }}-{% raw %}${{ github.event.inputs.version }}{% endraw %}/deploy/*.sha
{% break -%}
{% endif -%}
{% endfor %}

{% for platform in platforms -%}
{% if platform == "linux-arm64" or platform == "linux-arm" %}
  linux-arm64:
    name: 'Arm Linux {{ APP_NAME }} {% raw %}${{ github.event.inputs.version }}{% endraw %} publish release'
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 3
          submodules: true
      - name: 'Create body'
        run: |
          npm install
          cat scripts/templates/body-github-release-liquid.md | npm run liquidjs --silent -- '{ "RELEASE_VERSION": "{% raw %}${{ github.event.inputs.version }}{% endraw %}" }' >.github/workflows/body-github-release.md
          cat .github/workflows/body-github-release.md
      - name: 'Publish release'
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: '~/Work/{{ APP_LC_NAME }}-{% raw %}${{ github.event.inputs.version }}{% endraw %}/deploy/*'
          bodyFile: '.github/workflows/body-github-release.md'
          commit: 'master'
          draft: true
          name: 'xPack {{ APP_NAME }} v{% raw %}${{ github.event.inputs.version }}{% endraw %}'
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          owner: 'xpack-dev-tools'
          prerelease: true
          replacesArtifacts: true
          repo: '{{ APP_LC_NAME }}-xpack'
          tag: 'v{% raw %}${{ github.event.inputs.version }}{% endraw %}'
          token: {% raw %}${{ secrets.PUBLISH_TOKEN }}{% endraw %}
      - name: 'Show SHA'
        run: cat ~/Work/{{ APP_LC_NAME }}-{% raw %}${{ github.event.inputs.version }}{% endraw %}/deploy/*.sha
{% break -%}
{% endif -%}
{% endfor %}

{% for platform in platforms -%}
{% if platform == "darwin-x64" %}
  macos-x64:
    name: 'Intel macOS {{ APP_NAME }} {% raw %}${{ github.event.inputs.version }}{% endraw %} publish release'
    runs-on: [self-hosted, macOS, X64]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 3
          submodules: true
      - name: 'Create body'
        run: |
          npm install
          cat scripts/templates/body-github-release-liquid.md | npm run liquidjs --silent -- '{ "RELEASE_VERSION": "{% raw %}${{ github.event.inputs.version }}{% endraw %}" }' >.github/workflows/body-github-release.md
          cat .github/workflows/body-github-release.md
      - name: 'Publish release'
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: '~/Work/{{ APP_LC_NAME }}-{% raw %}${{ github.event.inputs.version }}{% endraw %}/deploy/*'
          bodyFile: '.github/workflows/body-github-release.md'
          commit: 'master'
          draft: true
          name: 'xPack {{ APP_NAME }} v{% raw %}${{ github.event.inputs.version }}{% endraw %}'
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          owner: 'xpack-dev-tools'
          prerelease: true
          replacesArtifacts: true
          repo: '{{ APP_LC_NAME }}-xpack'
          tag: 'v{% raw %}${{ github.event.inputs.version }}{% endraw %}'
          token: {% raw %}${{ secrets.PUBLISH_TOKEN }}{% endraw %}
      - name: 'Show SHA'
        run: cat ~/Work/{{ APP_LC_NAME }}-{% raw %}${{ github.event.inputs.version }}{% endraw %}/deploy/*.sha
{% break -%}
{% endif -%}
{% endfor %}
